import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useMemo } from "react";
import { MoneyAmount } from "../components/MoneyAmount";
export function Body({ billTo, items, taxRate, notes }) {
    const subtotal = useMemo(() => items.reduce((sum, item) => sum + item.unitPrice * item.qty, 0), [items]);
    return (_jsxs("section", { className: "invoice-body px-10 py-8 text-slate-800", children: [_jsxs("div", { className: "mb-8", children: [_jsx("div", { className: "text-xs uppercase tracking-widest text-slate-400 mb-1", children: "Billed to" }), _jsx("div", { className: "text-lg font-semibold", children: billTo.name }), billTo.company && (_jsx("div", { className: "text-slate-600", children: billTo.company })), _jsx("div", { className: "text-slate-600 whitespace-pre-line", children: billTo.address })] }), _jsxs("table", { className: "w-full text-sm border-collapse", children: [_jsx("thead", { children: _jsxs("tr", { className: "border-b-2 border-slate-900 text-left text-slate-500 uppercase text-xs tracking-wider", children: [_jsx("th", { className: "py-2 font-medium", children: "Description" }), _jsx("th", { className: "py-2 text-right font-medium", children: "Qty" }), _jsx("th", { className: "py-2 text-right font-medium", children: "Unit" }), _jsx("th", { className: "py-2 text-right font-medium", children: "Amount" })] }) }), _jsx("tbody", { children: items.map((item, i) => (_jsxs("tr", { className: "border-b border-slate-200", children: [_jsx("td", { className: "py-2", children: item.description }), _jsx("td", { className: "py-2 text-right tabular-nums", children: item.qty }), _jsx("td", { className: "py-2 text-right", children: _jsx(MoneyAmount, { amount: item.unitPrice }) }), _jsx("td", { className: "py-2 text-right", children: _jsx(MoneyAmount, { amount: item.unitPrice * item.qty }) })] }, i))) })] }), _jsx("div", { className: "flex justify-end mt-6", children: _jsxs("div", { className: "w-64 text-sm", children: [_jsxs("div", { className: "flex justify-between py-1 text-slate-600", children: [_jsx("span", { children: "Subtotal" }), _jsx(MoneyAmount, { amount: subtotal })] }), _jsxs("div", { className: "flex justify-between py-1 text-slate-600", children: [_jsxs("span", { children: ["Tax (", Math.round(taxRate * 100), "%)"] }), _jsx(MoneyAmount, { amount: subtotal * taxRate })] }), _jsxs("div", { className: "flex justify-between py-2 mt-1 border-t-2 border-slate-900 font-bold text-lg", children: [_jsx("span", { children: "Total" }), _jsx(MoneyAmount, { amount: subtotal * (1 + taxRate), bold: true })] })] }) }), notes && _jsx("p", { className: "mt-8 text-xs text-slate-400 italic", children: notes })] }));
}
export function Header({ companyName, companyEmail, invoiceNumber, issueDate, dueDate, }) {
    return (_jsxs("header", { className: "invoice-header bg-slate-900 text-white px-10 pt-8 pb-6 flex items-start justify-between", children: [_jsxs("div", { children: [_jsx("div", { className: "text-2xl font-bold tracking-tight", children: companyName }), _jsx("div", { className: "text-slate-300 text-sm mt-1", children: companyEmail })] }), _jsxs("div", { className: "text-right", children: [_jsx("div", { className: "text-xs uppercase tracking-[0.3em] text-slate-400", children: "Invoice" }), _jsx("div", { className: "text-xl font-semibold mt-0.5", children: invoiceNumber }), _jsxs("div", { className: "text-slate-300 text-sm mt-1", children: ["Issued ", issueDate] }), _jsxs("div", { className: "text-slate-300 text-sm", children: ["Due ", dueDate] })] })] }));
}
export function Footer({ thankYou, contactEmail, website, }) {
    return (_jsxs("footer", { className: "invoice-footer px-10 pt-6 pb-8 border-t border-slate-200 text-slate-500 text-sm flex items-center justify-between", children: [_jsx("div", { children: thankYou }), _jsxs("div", { className: "text-right", children: [_jsx("div", { children: contactEmail }), _jsx("div", { children: website })] })] }));
}
